### ISSUE TITLE
How to add a service to the setup?

### ISSUE THREAD

**Issue by thimplicity** [notthebee/ansible-easy-vpn#196]
Hi,
I know that this is definitely not an issue with the package itself. That works great and thanks for putting this together.

I would like to enhance the setup by adding ntfy to my setup. I am OK familiar with adding it to authelia, but I have no idea, how to add the subdomain to duckdns or get from the IP:port of the ntfy docker image to the URL. At home I use NPM for that, but I was not able to find the bunkerweb config files to check whether I can add it there. If that is the place to look.

Although it is not connected to your project, I would appreciate some guidance.

**Comment by MacchiaGuardala** [comment]
### newbie doubts about vaultwarden container:
On my vps I set [roles/bunkerweb/templates/env.j2](https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/bunkerweb/templates/env.j2) as @k-wlosek suggests, but trying to create the account for valutwarden I get an error about HTTPS required, while if I prepend https:// to domain:port I get SSL_ERROR_RX_RECORD_TOO_LONG
Will @Schwarzeisc00l from #129 succeed?

My docker-compose.yml for test
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    networks:
      - default
    restart: always
    container_name: vaultwarden
    ports:
      - 8080:80
    volumes:
      - ${PWD}/data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
```

I should read well and really understand this stuff at least:
- [bunkerweb quickstart](https://docs.bunkerweb.io/latest/quickstart-guide/#multiple-applications)
- [vaultwarden wiki](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-HTTPS)
- [search on vaultwarden discourse group](https://vaultwarden.discourse.group/search?q=https%20nginx) (ok, sorry...)
- ([issue about ROCKeT_TLS](https://github.com/rwf2/Rocket/issues/2363 ), suggested in https://vaultwarden.discourse.group/t/need-easy-step-by-steps-to-enable-https/1839/12?)
I doubt I can do it properly...
