### ISSUE TITLE
Error to run playhook

### ISSUE THREAD

**Issue by resie001** [notthebee/ansible-easy-vpn#39]
```ERROR! couldn't resolve module/action 'ufw'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/ansible-easy-vpn/roles/ufw/tasks/main.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Enable UFW logging
  ^ here
```

i use Linux Ubuntu 20.04 X86 64

**Comment by notthebee** [comment]
The part of the log that mentions why the error is is missing. Should be just above what you pasted.

**Comment by resie001** [comment]
> The part of the log that mentions what the error is is missing. Should be just above what you pasted.

I open ansible-easy-vpn/roles/ufw/tasks/main.yml 
```
- name: Install UFW
  package:
    name: ufw
    state: present

- name: Enable UFW logging
  ufw:
    logging: on

- name: Allow the defined ports
  ufw:
    rule: allow
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  with_items:
    - "{{ ufw_ports }}"

```

so which part that i must change? i have zero knowledge about this stuff. I check this yaml with yaml lint and it say Ok.
